# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd1ec6ce8a8f9113a6472c5e9abd9b101f3360cbb8d6625ffb5e3e8d7c479748fa681c9df3238b97bb79051b5b175b675e7b736c1f3298820897db2afe21460c

test:
  secret_key_base: d6af2f1ed570441abb2d9ee7edd8b3d467798d14444e7e3f90ca9a707b6b6610a90e16994c290e7e964d46ef1e1eec99ca1e79e84cccf7e9589f3096a248cae8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
